# Generated by Django 3.2.7 on 2021-09-05 05:05

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('formpage1', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SmsCodeModel',
            fields=[
                ('smscode_id', models.IntegerField(default=0, editable=False, primary_key=True, serialize=False)),
                ('operation_type', models.IntegerField()),
                ('token', models.UUIDField(default=uuid.uuid4, editable=False)),
                ('phone', models.CharField(max_length=20)),
                ('code_hash', models.CharField(max_length=50)),
                ('client_id', models.CharField(max_length=15)),
                ('create_time', models.DateTimeField(auto_now_add=True)),
                ('sms_id', models.IntegerField()),
                ('expiration_time', models.DateTimeField()),
                ('delivered_time', models.DateTimeField(null=True)),
                ('attempts', models.IntegerField(default=0)),
                ('confirm_time', models.DateTimeField(null=True)),
                ('session_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='formpage1.sessionmodel', verbose_name='Сессия')),
            ],
            options={
                'verbose_name': 'СМС код',
                'verbose_name_plural': 'СМС коды',
            },
        ),
        migrations.CreateModel(
            name='SmsJustifications',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('justification_id', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='formpage1.justifications')),
                ('smscode_id', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='smsservice.smscodemodel', verbose_name='Сессия')),
            ],
            options={
                'verbose_name': 'СМС одобрения',
                'verbose_name_plural': 'СМС одобрений',
            },
        ),
    ]
