# Generated by Django 3.2.7 on 2021-09-05 05:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Justifications',
            fields=[
                ('justifications_id', models.IntegerField(default=0, editable=False, primary_key=True, serialize=False)),
                ('justification_type', models.IntegerField()),
            ],
            options={
                'verbose_name': 'Одобрения',
                'verbose_name_plural': 'Одобрений',
            },
        ),
        migrations.CreateModel(
            name='SessionModel',
            fields=[
                ('session_id', models.BigIntegerField(primary_key=True, serialize=False)),
                ('session', models.CharField(max_length=64)),
                ('create_time', models.DateTimeField(auto_now_add=True)),
                ('expiration_time', models.DateTimeField()),
                ('auth_type', models.IntegerField()),
                ('justification_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='justification_id', to='formpage1.justifications')),
            ],
            options={
                'verbose_name': 'Сессия',
                'verbose_name_plural': 'Сессий',
            },
        ),
        migrations.CreateModel(
            name='PersonPage',
            fields=[
                ('client_id', models.AutoField(primary_key=True, serialize=False)),
                ('iin', models.CharField(max_length=15)),
                ('phone', models.CharField(max_length=20)),
                ('password_hash', models.CharField(max_length=64)),
                ('surname', models.CharField(max_length=100)),
                ('name', models.CharField(max_length=100)),
                ('patronimyc', models.CharField(max_length=100, null=True)),
                ('create_time', models.DateTimeField(auto_now_add=True)),
                ('update_time', models.DateTimeField()),
                ('justification_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='formpage1.justifications')),
                ('session_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='formpage1.sessionmodel')),
            ],
            options={
                'verbose_name': 'ИИН',
                'verbose_name_plural': 'ИИН',
            },
        ),
        migrations.CreateModel(
            name='PersonLeads',
            fields=[
                ('clientLead_id', models.IntegerField(primary_key=True, serialize=False)),
                ('iin', models.CharField(max_length=12)),
                ('phone', models.CharField(max_length=20)),
                ('urname', models.CharField(max_length=100)),
                ('name', models.CharField(max_length=100)),
                ('patronimyc', models.CharField(max_length=100, null=True)),
                ('create_time', models.DateTimeField(auto_now_add=True)),
                ('update_time', models.DateTimeField()),
                ('personal_data_success', models.BooleanField()),
                ('session_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='formpage1.sessionmodel')),
            ],
            options={
                'verbose_name': 'ИИН Lead',
                'verbose_name_plural': 'ИИН Leads',
            },
        ),
        migrations.CreateModel(
            name='PersonBiometrics',
            fields=[
                ('clientBiometric_id', models.IntegerField(primary_key=True, serialize=False)),
                ('client_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='formpage1.personpage')),
            ],
            options={
                'verbose_name': 'Биометрия',
                'verbose_name_plural': 'Биометрия',
            },
        ),
    ]
