# Generated by Django 3.2.7 on 2021-09-05 05:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('formpage1', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='personleads',
            name='session_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='personlead_session_id', to='formpage1.sessionmodel'),
        ),
        migrations.AlterField(
            model_name='personpage',
            name='justification_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='person_justification_id', to='formpage1.justifications'),
        ),
        migrations.AlterField(
            model_name='personpage',
            name='session_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='person_session_id', to='formpage1.sessionmodel'),
        ),
        migrations.AlterField(
            model_name='sessionmodel',
            name='justification_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='session_justification_id', to='formpage1.justifications'),
        ),
    ]
