# Generated by Django 3.2.7 on 2021-09-06 15:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('formpage1', '0003_auto_20210906_1502'),
    ]

    operations = [
        migrations.RenameField(
            model_name='leads',
            old_name='clientLead_id',
            new_name='lead_id',
        ),
    ]
