# Generated by Django 3.2.7 on 2021-09-06 15:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('formpage1', '0004_rename_clientlead_id_leads_lead_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='leads',
            name='lead_id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='leads',
            name='session_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='lead_session_id', to='formpage1.sessionmodel'),
        ),
        migrations.AlterField(
            model_name='personpage',
            name='iin',
            field=models.CharField(max_length=12),
        ),
    ]
