# Generated by Django 3.2.7 on 2021-09-06 16:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('formpage1', '0006_alter_sessionmodel_session_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sessionmodel',
            name='auth_type',
            field=models.IntegerField(null=True),
        ),
    ]
